### PR TITLE
Fix the profile

### LINKED ISSUE #69: fix the profile
fix the errors in the profile and use filter to fetch only the user's posts.
and fix the styling.

### PR DESCRIPTION
**Pull request by ZhinAbubakr**

### CODE REVIEW

File: src/components/Profile/Profile.jsx [hunk 1]
```diff
@@ -39,6 +46,7 @@ export default function InsetDividers() {
                 <CardMedia
                   className={classes.media}
                   image="https://miro.medium.com/max/1200/1*mk1-6aYaf_Bes1E3Imhc0A.jpeg"
```
Comment (Othmanosx) [inline src/components/Profile/Profile.jsx:48]: Download the image and import it in the project instead of using external links.

File: src/components/Profile/Profile.jsx [hunk 2]
```diff
@@ -106,19 +114,21 @@ export default function InsetDividers() {
...
           </Grid>
           <Grid item xs={12} className={classes.btn2}>
-            <Button
-              variant="contained"
-              color="secondary"
-              style={{ fontWeight: "bold" }}
-            >
-              Add Post
-            </Button>
+            <Link to={'/form'} className={classes.links}>
```
Comment (Othmanosx) [inline src/components/Profile/Profile.jsx]: import and use the route names from route.js file like this:

```
import FORM_ROUTE from ".../routes.js";
<Link to={FORM_ROUTE} className={classes.links}>
```

**Review by Othmanosx — CHANGES_REQUESTED** [review]
Nice work! I have added some comments, let me know what you think.

File: src/components/Profile/Profile.jsx [hunk 3]
```diff
@@ -141,13 +151,15 @@ export default function InsetDividers() {
...
-              style={{ fontWeight: "bold" }}
-            >
-              Add Post
-            </Button>
+            <Link to={"/form"} className={classes.links}>
+              <Button
+                variant="contained"
+                color="secondary"
+                style={{ fontWeight: "bold" }}
+              >
```
Comment (murtaja1) [inline src/components/Profile/Profile.jsx:160]: try not to have inline styling

**Review by murtaja1 — APPROVED** [review]

**Review by maqalaqil — APPROVED** [review]

**Review by Othmanosx — APPROVED** [review]
